
name: GitHub Actions Demo
on: [push]
      branches: 
       - dev
jobs:
    builds:
      runs-on: windows-latest
      steps:
       - uses: actions/checkout@v2
        - run: echo "The job was automatically triggered by a ${{ gitbuh.event_name}} event."
        - run: python main.py